# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
changelog:
  categories:
    - title: 'Benchmarks'
      labels:
        - 'benchmarks'
    - title: 'Alpakka Kafka core'
      labels:
        - 'core'
    - title: 'Tests'
      labels:
        - 'tests'
    - title: 'Alpakka Kafka Testkit'
      labels:
        - 'testkit'
    - title: 'Documentation'
      labels:
        - 'documentation'
    - title: 'Other'
      labels:
        - "*"
