name: Dependency Graph submission

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags: ["*"]

permissions:
  contents: read

jobs:
  dependency-graph:
    name: Update Dependency Graph
    if: github.event.repository.fork == false
    runs-on: Akka-Default
    permissions:
      contents: write
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run akka/github-actions-scripts
        uses: akka/github-actions-scripts/setup_global_resolver@main

      - name: Submit dependencies to GitHub
        # https://github.com/scalacenter/sbt-dependency-submission/releases
        uses: scalacenter/sbt-dependency-submission@v3.2.1
        with:
          modules-ignore: akka-stream-kafka-benchmarks_2.13 akka-stream-kafka-benchmarks_3 akka-stream-kafka-tests_2.13 akka-stream-kafka-tests_3
          configs-ignore: test It
