name: Dependency Graph submission

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags: ["*"]

permissions:
  contents: read

jobs:
  dependency-graph:
    name: Update Dependency Graph
    if: github.event.repository.fork == false
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v3.5.0
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 0
      - name: Submit dependencies to GitHub
        # https://github.com/scalacenter/sbt-dependency-submission/releases
        # v2.1.2
        uses: scalacenter/sbt-dependency-submission@c1a4bf7781721f012d92248cc7da60655d2e2880
        with:
          modules-ignore: akka-stream-kafka-benchmarks_2.13 akka-stream-kafka-tests_2.13
          configs-ignore: test It
