name: Dependency License Scanning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday

permissions:
  contents: read # allow actions/checkout

jobs:
  fossa:
    name: Fossa
    runs-on: Akka-Default
    if: github.repository == 'akka/alpakka-kafka'
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Run akka/github-actions-scripts
        uses: akka/github-actions-scripts/setup_global_resolver@main

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.17

      - name: FOSSA policy check
        run: |-
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          fossa analyze && fossa test
        env:
          FOSSA_API_KEY: "${{secrets.FOSSA_API_KEY}}"
