# https://github.com/marketplace/actions/labeler

name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/actions/labeler/releases
      # v5.0.0
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
