name: Publish Artifacts

on:
  push:
    branches:
      - master
      - main
      - seglo/actions # FIXME: remove
      - release-*
    tags: [ v.* ]

jobs:
  publish:
    # runs on main repo only
    if: github.repository == 'akka/alpakka-kafka'
    name: Publish Artifacts
    # the release environment provides access to secrets required in the release process
    # https://github.com/akka/alpakka-kafka/settings/environments/84275678/edit
    environment: release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Scala with JDK 8
        uses: olafurpg/setup-scala@v10

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Publish artifacts for all Scala versions
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: sbt "+publish"

      - name: Publish API and reference documentation
        env:
          GUSTAV_KEY: ${{ secrets.GUSTAV_KEY }}
        run: |+
          cat $GUSTAV_KEY > .github/id_rsa
          eval "$(ssh-agent -s)"
          chmod 600 .github/id_rsa
          ssh-add .github/id_rsa
          sbt -jvm-opts .jvmopts-travis '++2.13.2 docs/publishRsync'
