name: Scheduled Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    if: github.repository == 'akka/alpakka-kafka'
    strategy:
      fail-fast: false
      matrix:
        include:
          # cover relevant combinations not covered in `check-build-test.yml`
          # { scalaVersion: "2.12", jdkVersion: "1.8.0",  jvmName: "temurin:1.8.0",  extraOpts: '' }
          - { scalaVersion: "2.12", jdkVersion: "1.11.0", jvmName: "temurin:1.11.0", extraOpts: '-J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler' }
          - { scalaVersion: "2.12", jdkVersion: "1.17.0", jvmName: "temurin:1.17.0", extraOpts: '' }
          - { scalaVersion: "2.13", jdkVersion: "1.8.0",  jvmName: "temurin:1.8.0", extraOpts: '' }
          # { scalaVersion: "2.13", jdkVersion: "1.11.0", jvmName: "temurin:1.11.0", extraOpts: '-J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler' }
          - { scalaVersion: "2.13", jdkVersion: "1.17.0", jvmName: "temurin:1.17.0", extraOpts: '' }
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Set up JDK ${{ matrix.jdkVersion }}
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: ${{ matrix.jvmName }}

      - name: sbt test
        run: sbt ++${{ matrix.scalaVersion }} \
          test ${{ matrix.extraOpts }}

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
