name: Build and Test (Java 8)

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Scala with JDK 8
        uses: olafurpg/setup-scala@v10

      - name: "Run tests with Scala 2.12 and AdoptOpenJDK 8"
        run: sbt "++2.12.11 test"

      - name: "Run tests with Scala 2.13 and AdoptOpenJDK 8"
        run: sbt "++2.13.2 test"